services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goshort
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - internal
  goshort:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_HOST: mysql
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_NAME: goshort
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge